# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec202e7b05e3d2c09bc074632dec719a352900df5b7a604d7e5c6b46d85a7f8020d5b94acd06760afa6ab69ebc899e179f1292f1c1020d6dd4c24db5973244b3

test:
  secret_key_base: b1df1ca60060caa607a2dac4cae1c5f2497f76e585048d35b29298862d340c9bb0117d8ea0aacfb5605b5018156c67278c8523644ca3a38ea1fddbd6724522dc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
